theme: jekyll-theme-cayman
name: Nilesh Salpe's Blog
description: Sharing tidbits of my experience from tech world !!!
# Google Analytics
google_analytics: G-BY6V02HSE8
comments: true
markdown: kramdown
