theme: jekyll-theme-cayman
name: Nilesh Salpe's Blog
description: Sharing tidbits of my experience from tech world !!!
# Google Analytics
google_analytics: G-BY6V02HSE8
comments: true
markdown: kramdown
# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: fortunan
# Use the following plug-ins
#gems:
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: nileshsalpe
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  
# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account.
disqus: nileshsalpe
